name: Auto Tag Release

on:
  push:
    branches:
      - main

permissions:
  contents: write  # This is critical - allows writing to the repository

jobs:
  auto-tag:
    runs-on: ubuntu-latest
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      # Rest of your workflow...